# Generated by Django 2.0.12 on 2020-06-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
