# Generated by Django 2.0.12 on 2020-06-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
